# Generated by Django 3.1 on 2021-03-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='позиция'),
        ),
    ]
