# Generated by Django 3.1 on 2021-03-13 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20210312_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-id'], 'verbose_name': 'опрос', 'verbose_name_plural': 'опросы'},
        ),
    ]
