# Generated by Django 3.1 on 2021-03-13 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_auto_20210313_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-id'], 'verbose_name': 'ответ', 'verbose_name_plural': 'ответы'},
        ),
        migrations.AlterModelOptions(
            name='choicequestion',
            options={'base_manager_name': 'objects', 'verbose_name': 'вопрос с одиночным выбором', 'verbose_name_plural': 'вопросы с одиночным выбором'},
        ),
        migrations.AlterModelOptions(
            name='inputchoicequestion',
            options={'base_manager_name': 'objects', 'verbose_name': 'вопрос с одиночным выбором и пользовательским вводом', 'verbose_name_plural': 'вопросы с одиночным выбором и пользовательским вводом'},
        ),
        migrations.AlterModelOptions(
            name='inputmultichoicequestion',
            options={'base_manager_name': 'objects', 'verbose_name': 'вопрос с множественным выбором и пользовательским вводом', 'verbose_name_plural': 'вопросы с множественным выбором и пользовательским вводом'},
        ),
        migrations.AlterModelOptions(
            name='inputquestion',
            options={'base_manager_name': 'objects', 'verbose_name': 'вопрос с пользовательским вводом', 'verbose_name_plural': 'вопросы с пользовательским вводом'},
        ),
        migrations.AlterModelOptions(
            name='multichoicequestion',
            options={'base_manager_name': 'objects', 'verbose_name': 'вопрос с множественным выбором', 'verbose_name_plural': 'вопросы с множественным выбором'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'ordering': ['-id'], 'verbose_name': 'ответ пользователя', 'verbose_name_plural': 'ответы пользователя'},
        ),
        migrations.AlterModelOptions(
            name='userchoiceanswer',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='userinputanswer',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='usermultichoiceanswer',
            options={'base_manager_name': 'objects'},
        ),
    ]
