# Generated by Django 3.1 on 2021-03-16 08:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_auto_20210313_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='end_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата окончания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='start_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата начала'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'ожидает'), (1, 'активен'), (2, 'завершен')], default=0, verbose_name='статус опроса'),
        ),
    ]
